select 
Union_Id,
Tenant_Id,
Tenant_Name,
Record_Type,
cast(Record_Id as varchar(128)) Record_Id,
Record_Last_Modification_Date_Time,
Is_Deleted,
Module_Reference_Id,
Record_Name,
Record_Description,
Record_Status,
Record_Due_Date_Time,
Record_Overdue,
Record_Subtype,
Assigned_Owners,
[Access_Members], 
[Tags],
TenantVendorId,
Additional_Info
from {{ ref("Condensed_assessments") }}

union all
select
Union_Id,
Tenant_Id,
Tenant_Name,
Record_Type,
cast(Record_Id as varchar(128)) Record_Id,
Record_Last_Modification_Date_Time,
Is_Deleted,
Module_Reference_Id,
Record_Name,
Record_Description,
Record_Status,
Record_Due_Date_Time,
Record_Overdue,
Record_Subtype,
Assigned_Owners,
[Access_Members], 
[Tags],
TenantVendorId,
Additional_Info
from {{ ref("Condensed_third_parties") }}
union all
select
Union_Id,
Tenant_Id,
Tenant_Name,
Record_Type,
cast(Record_Id as varchar(128)) Record_Id,
Record_Last_Modification_Date_Time,
Is_Deleted,
Module_Reference_Id,
Record_Name,
Record_Description,
Record_Status,
Record_Due_Date_Time,
Record_Overdue,
Record_Subtype,
Assigned_Owners,
[Access_Members], 
[Tags],
TenantVendorId,
Additional_Info
from {{ ref("Condensed_assets") }}
union all
select
Union_Id,
Tenant_Id,
Tenant_Name,
Record_Type,
cast(Record_Id as varchar(128)) Record_Id,
Record_Last_Modification_Date_Time,
Is_Deleted,
Module_Reference_Id,
Record_Name,
Record_Description,
Record_Status,
Record_Due_Date_Time,
Record_Overdue,
Record_Subtype,
Assigned_Owners,
[Access_Members], 
[Tags],
TenantVendorId,
Additional_Info
from {{ ref("Condensed_custom_registers") }}
union all
select
Union_Id,
Tenant_Id,
Tenant_Name,
Record_Type,
cast(Record_Id as varchar(128)) Record_Id,
Record_Last_Modification_Date_Time,
Is_Deleted,
Module_Reference_Id,
Record_Name,
Record_Description,
Record_Status,
Record_Due_Date_Time,
Record_Overdue,
Record_Subtype,
Assigned_Owners,
[Access_Members], 
[Tags],
TenantVendorId,
Additional_Info
from {{ ref("Condensed_issues") }}
union all
select
Union_Id,
Tenant_Id,
Tenant_Name,
Record_Type,
cast(Record_Id as varchar(128)) Record_Id,
Record_Last_Modification_Date_Time,
Is_Deleted,
Module_Reference_Id,
Record_Name,
Record_Description,
Record_Status,
Record_Due_Date_Time,
Record_Overdue,
Record_Subtype,
Assigned_Owners,
[Access_Members], 
[Tags],
TenantVendorId,
Additional_Info
from {{ ref("Condensed_risks") }}
union all
select
Union_Id,
Tenant_Id,
Tenant_Name,
Record_Type,
cast(Record_Id as varchar(128)) Record_Id,
Record_Last_Modification_Date_Time,
Is_Deleted,
Module_Reference_Id,
Record_Name,
Record_Description,
Record_Status,
Record_Due_Date_Time,
Record_Overdue,
Record_Subtype,
Assigned_Owners,
[Access_Members], 
[Tags],
TenantVendorId,
Additional_Info
from {{ ref("Condensed_authorities") }}
union all
select
Union_Id,
Tenant_Id,
Tenant_Name,
Record_Type,
cast(Record_Id as varchar(128)) Record_Id,
Record_Last_Modification_Date_Time,
Is_Deleted,
Module_Reference_Id,
Record_Name,
Record_Description,
Record_Status,
Record_Due_Date_Time,
Record_Overdue,
Record_Subtype,
Assigned_Owners,
[Access_Members], 
[Tags],
TenantVendorId,
Additional_Info
from {{ ref("Condensed_controls") }}
union all
select
Union_Id,
Tenant_Id,
Tenant_Name,
Record_Type,
cast(Record_Id as varchar(128)) Record_Id,
Record_Last_Modification_Date_Time,
Is_Deleted,
Module_Reference_Id,
Record_Name,
Record_Description,
Record_Status,
Record_Due_Date_Time,
Record_Overdue,
Record_Subtype,
Assigned_Owners,
[Access_Members], 
[Tags],
TenantVendorId,
Additional_Info
from {{ ref("Condensed_projects") }}