{{ config(materialized="view") }}
with
    base as (
        select
            [Id],
            [AccessFailedCount],
            [AuthenticationSource],
            [ConcurrencyStamp],
            [CreationTime],
            [CreatorUserId],
            [DeleterUserId],
            [DeletionTime],
            [EmailAddress],
            [EmailConfirmationCode],
            [Name] + ' ' + [Surname] FullName,
            [IsActive],
            [IsDeleted],
            [IsEmailConfirmed],
            [IsLockoutEnabled],
            [IsPhoneNumberConfirmed],
            [IsTwoFactorEnabled],
            [LastLoginTime],
            [LastModificationTime],
            [LastModifierUserId],
            [LockoutEndDateUtc],
            [Name],
            [NormalizedEmailAddress],
            [NormalizedUserName],
            [Password],
            [PasswordResetCode],
            [PhoneNumber],
            [ProfilePictureId],
            [SecurityStamp],
            [ShouldChangePasswordOnNextLogin],
            [Surname],
            [TenantId],
            [UserName],
            cast([SignInToken] as nvarchar(4000)) SignInToken,
            [SignInTokenExpireTimeUtc],
            cast([GoogleAuthenticatorKey] as nvarchar(4000)) GoogleAuthenticatorKey,
            [AcceptTerms],
            [IsInvitedAdvisor],
            cast([JobTitle] as nvarchar(4000)) JobTitle,
            [LocationId],
            [HasLoggedInUsingWebApp],
            [IsMobilesa],
            [IsWebsa],
            [IsHidden],
            [HasLoggedInUsingMobileApp],
            [LicenseType],
            cast([AreaOfResponsibility] as nvarchar(4000)) AreaOfResponsibility,
            [ReportingPlatformId],
            cast(coalesce(LastModificationTime,CreationTime) as datetime2) as UpdateTime
        from {{ source("assessment_models", "AbpUsers") }} {{ system_remove_IsDeleted() }}
    )

select
    {{ col_rename("Id", "AbpUsers") }},
    {{ col_rename("Name", "AbpUsers") }},
    {{ col_rename("CreationTime", "AbpUsers") }},
    {{ col_rename("LastModificationTime", "AbpUsers") }},
    {{ col_rename("EmailAddress", "AbpUsers") }},
    {{ col_rename("NormalizedEmailAddress", "AbpUsers") }},
    {{ col_rename("NormalizedUserName", "AbpUsers") }},

    {{ col_rename("UserName", "AbpUsers") }},
    {{ col_rename("Surname", "AbpUsers") }},
    {{ col_rename("FullName", "AbpUsers") }},
    {{ col_rename("TenantId", "AbpUsers") }},
    {{ col_rename("ReportingPlatformId", "AbpUsers") }},
    {{ col_rename("LastLoginTime", "AbpUsers") }},
    {{ col_rename("UpdateTime", "AbpUsers") }}
from base
