name: 'sixclicks_dev_orig'
version: '1.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project. Profiles contain
# database connection information, and should be configured in the  ~/.dbt/profiles.yml file
profile: 6clicks_dev

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that source models can be found
# in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "public"

models:
  sixclicks_dev_orig:
    +on_schema_change: "append_new_columns" # Change from 'ignore' to this

dispatch:
  - macro_namespace: dbt_utils
    search_order: ['tsql_utils', 'dbt_utils']
  - macro_namespace: dbt_date
    search_order: ['tsql_utils', 'dbt_date']
  # - macro_namespace: dbt_expectations
  #   search_order: ['tsql_utils', 'dbt_expectations']
  # - macro_namespace: audit_helper
  #   search_order: ['tsql_utils', 'audit_helper']